version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: nutshell_web_1
      APP_PORT: 3338
      PROXY_AUTH_ADD: 'false'
    container_name: nutshell_app_proxy_1
  web:
    image: >-
      cashubtc/nutshell:0.17.0@sha256:56b85add2e05ca364ee3fb8cab9ea0fc514f2fa0dff62dd85b5422fbb7b7874b
    init: true
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_LIGHTNING_NODE_DATA_DIR}:/lnd:ro
    command:
      - poetry
      - run
      - mint
    environment:
      MINT_DATABASE: /data
      MINT_LISTEN_PORT: 3338
      MINT_LISTEN_HOST: 0.0.0.0
      MINT_PRIVATE_KEY: ${APP_SEED}
      MINT_BACKEND_BOLT11_SAT: LndRestWallet
      MINT_LND_REST_ENDPOINT: https://$APP_LIGHTNING_NODE_IP:$APP_LIGHTNING_NODE_REST_PORT/
      MINT_LND_REST_CERT: /lnd/tls.cert
      MINT_LND_REST_MACAROON: /lnd/data/chain/bitcoin/$APP_BITCOIN_NETWORK/admin.macaroon
      MINT_INFO_NAME: Umbrel Cashu mint
      MINT_INFO_DESCRIPTION: A cashu mint running on Umbrel
      MINT_INFO_DESCRIPTION_LONG: A cashu mint running on Umbrel
      MINT_INFO_URLS: '["http://umbrel.local", "${APP_HIDDEN_SERVICE}"]'
      TOR_PROXY_IP: ${TOR_PROXY_IP}
      TOR_PROXY_PORT: ${TOR_PROXY_PORT}
    container_name: nutshell_web_1